name: "my first workflow"

on:
 push:
   branches:
     - 'features/**'
     - 'main'
     - 'hotflix/**'

jobs:
  terraformInit: 
    name: Terrafrom Initwa
    runs-on: self-hosted
    steps:
    - name: Dhondhu Maharaj  Rocks
      run: echo Dhondhu Maharaj
      
    
    
     
 
 
